/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options */
        get: operations["options_api_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Content Generate */
        post: operations["content_generate_api_content_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Legacy Generate */
        post: operations["legacy_generate_api_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Campaign Generate */
        post: operations["campaign_generate_api_campaigns_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapter-promos/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chapter Promos Generate */
        post: operations["chapter_promos_generate_api_chapter_promos_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drafts */
        get: operations["list_drafts_api_drafts_get"];
        put?: never;
        /** Create Draft */
        post: operations["create_draft_api_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_drafts__draft_id__get"];
        /** Put Draft */
        put: operations["put_draft_api_drafts__draft_id__put"];
        post?: never;
        /** Delete Draft */
        delete: operations["delete_draft_api_drafts__draft_id__delete"];
        options?: never;
        head?: never;
        /** Patch Draft */
        patch: operations["patch_draft_api_drafts__draft_id__patch"];
        trace?: never;
    };
    "/api/podcasts/scripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Script */
        post: operations["create_script_api_podcasts_scripts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/podcasts/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Legacy Create Script */
        post: operations["legacy_create_script_api_podcasts_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/podcasts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Podcast */
        get: operations["get_podcast_api_podcasts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Podcast */
        patch: operations["update_podcast_api_podcasts__draft_id__patch"];
        trace?: never;
    };
    "/api/podcasts/{draft_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Podcast Preview */
        post: operations["podcast_preview_api_podcasts__draft_id__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/podcasts/{draft_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Podcast Render */
        post: operations["podcast_render_api_podcasts__draft_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Export */
        post: operations["create_export_api_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{artifact_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_api_artifacts__artifact_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Voices */
        get: operations["voices_api_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/{voice_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voice Preview */
        post: operations["voice_preview_api_voices__voice_id__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["job_status_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gallery/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gallery Images */
        get: operations["gallery_images_api_gallery_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audio Library */
        get: operations["audio_library_api_library_audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Artifact */
        Artifact: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /** Filename */
            filename: string;
            /**
             * Media Type
             * @default application/octet-stream
             */
            media_type: string;
        };
        /** CampaignGenerationRequest */
        CampaignGenerationRequest: {
            /** Topic */
            topic: string;
            /** Content Types */
            content_types: string[];
            /**
             * Related Book
             * @default
             */
            related_book: string;
            /**
             * Platform
             * @default
             */
            platform: string;
            /** Audience */
            audience?: string[];
            /** Objectives */
            objectives?: string[];
            /** Constraints */
            constraints?: string[];
            /**
             * Cta
             * @default
             */
            cta: string;
        };
        /** ChapterPromoRequest */
        ChapterPromoRequest: {
            /** Books */
            books: string[];
            /** Chapters */
            chapters: string[];
            /** Platforms */
            platforms?: string[];
            /**
             * Mode
             * @default Tease It
             */
            mode: string;
            /**
             * Genre
             * @default Horror
             */
            genre: string;
            /**
             * Promotional Goal
             * @default Read the Next Chapter
             */
            promotional_goal: string;
            /** Moods */
            moods?: string[];
            /**
             * Style Variant
             * @default spoiler_safe_teaser
             */
            style_variant: string;
            /**
             * Spoiler Level
             * @default Almost Nothing
             */
            spoiler_level: string;
            /**
             * Spoiler Notes
             * @default
             */
            spoiler_notes: string;
            /**
             * Cta
             * @default
             */
            cta: string;
            /**
             * Optional Quote
             * @default
             */
            optional_quote: string;
            /** Hooks */
            hooks?: string[];
            /**
             * Focus Character
             * @default
             */
            focus_character: string;
            /**
             * Teaser Pillar
             * @default Choose the Best Structure for Me
             */
            teaser_pillar: string;
            /**
             * Promo Duration
             * @default 30-Second Chapter Promo
             */
            promo_duration: string;
            /**
             * Genre Promo Mode
             * @default Match the Chapter Automatically
             */
            genre_promo_mode: string;
            /** Promo Outputs */
            promo_outputs?: string[];
        };
        /** ContentGenerationRequest */
        ContentGenerationRequest: {
            /** Content Type */
            content_type: string;
            /** Topic */
            topic: string;
            /**
             * Related Book
             * @default
             */
            related_book: string;
            /** Related Books */
            related_books?: string[];
            /**
             * Platform
             * @default
             */
            platform: string;
            /** Audience */
            audience?: string[];
            /** Objectives */
            objectives?: string[];
            /** Constraints */
            constraints?: string[];
            /**
             * Cta
             * @default
             */
            cta: string;
            /** Formats */
            formats?: string[];
            /** Visual Formats */
            visual_formats?: string[];
            /**
             * Visual Style
             * @default
             */
            visual_style: string;
            /**
             * Image Source
             * @default
             */
            image_source: string;
            /**
             * Hashtag Mode
             * @default
             */
            hashtag_mode: string;
            /**
             * Blog Length
             * @default
             */
            blog_length: string;
            /**
             * Blog Format
             * @default
             */
            blog_format: string;
            /** Structure */
            structure?: string[];
            /**
             * Spoiler Level
             * @default
             */
            spoiler_level: string;
            /**
             * Source Restrictions
             * @default
             */
            source_restrictions: string;
            /**
             * Length Preference
             * @default
             */
            length_preference: string;
            /**
             * Supporting Image
             * @default
             */
            supporting_image: string;
            /**
             * Image Generation
             * @default
             */
            image_generation: string;
            /**
             * Word Count
             * @default
             */
            word_count: string;
            /**
             * Seo Keyword
             * @default
             */
            seo_keyword: string;
            /**
             * Heading Depth
             * @default
             */
            heading_depth: string;
            /**
             * Metadata Controls
             * @default
             */
            metadata_controls: string;
            /** Knowledge Sources */
            knowledge_sources?: string[];
            /**
             * Source Focus
             * @default
             */
            source_focus: string;
            /**
             * Press Timing
             * @default
             */
            press_timing: string;
            /**
             * Publication Date
             * @default
             */
            publication_date: string;
            /**
             * Byline City
             * @default
             */
            byline_city: string;
            /**
             * News Angle
             * @default
             */
            news_angle: string;
            /**
             * Auto News Angle
             * @default false
             */
            auto_news_angle: boolean;
            /**
             * Boilerplate
             * @default
             */
            boilerplate: string;
            /**
             * Auto Boilerplate
             * @default false
             */
            auto_boilerplate: boolean;
            /**
             * Media Contact
             * @default
             */
            media_contact: string;
            /**
             * Media Contact Name
             * @default
             */
            media_contact_name: string;
            /**
             * Media Contact Email
             * @default
             */
            media_contact_email: string;
            /**
             * Media Contact Phone
             * @default
             */
            media_contact_phone: string;
            /**
             * Media Contact Website
             * @default
             */
            media_contact_website: string;
            /** Companion Assets */
            companion_assets?: string[];
        };
        /** Draft */
        Draft: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Content Type */
            content_type: string;
            /**
             * Status
             * @default Draft
             */
            status: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
            /**
             * Path
             * @default
             */
            path: string;
            /**
             * Source Path
             * @default
             */
            source_path: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Content
             * @default
             */
            content: string;
        };
        /** DraftCreateRequest */
        DraftCreateRequest: {
            /** Title */
            title: string;
            /** Content */
            content: string;
            /**
             * Status
             * @default Draft
             */
            status: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Content Type
             * @default content
             */
            content_type: string;
            /**
             * Source Path
             * @default
             */
            source_path: string;
        };
        /** DraftUpdateRequest */
        DraftUpdateRequest: {
            /** Title */
            title: string;
            /** Content */
            content: string;
            /**
             * Status
             * @default Draft
             */
            status: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** ExportRequest */
        ExportRequest: {
            /** Title */
            title: string;
            /** Content */
            content: string;
            /**
             * Format
             * @default docx
             * @enum {string}
             */
            format: "docx" | "markdown" | "txt";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "running" | "complete" | "failed";
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Result */
            result?: {
                [key: string]: unknown;
            };
        };
        /** PerformanceCue */
        PerformanceCue: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /**
             * Value
             * @default
             */
            value: string;
        };
        /** PodcastDraft */
        PodcastDraft: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Content Type
             * @default podcast
             */
            content_type: string;
            /**
             * Status
             * @default Draft
             */
            status: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
            /**
             * Path
             * @default
             */
            path: string;
            /**
             * Source Path
             * @default
             */
            source_path: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Show Title
             * @default
             */
            show_title: string;
            /**
             * Episode Title
             * @default
             */
            episode_title: string;
            /** Speakers */
            speakers?: components["schemas"]["PodcastSpeaker"][];
            /** Segments */
            segments?: components["schemas"]["PodcastSegment"][];
            /** Raw Script */
            raw_script?: string | null;
        };
        /** PodcastGenerationRequest */
        PodcastGenerationRequest: {
            /** Topic */
            topic: string;
            /**
             * Source Title
             * @default
             */
            source_title: string;
            /**
             * Show Title
             * @default
             */
            show_title: string;
            /**
             * Episode Title
             * @default
             */
            episode_title: string;
            /**
             * Episode Number
             * @default
             */
            episode_number: string;
            /**
             * Destination
             * @default Spotify
             */
            destination: string;
            /**
             * Podcast Format
             * @default roundtable discussion
             */
            podcast_format: string;
            /**
             * Speakers
             * @default 3
             */
            speakers: string;
            /**
             * Speaker Roles
             * @default Host, Co-host, Guest
             */
            speaker_roles: string;
            /** Tone */
            tone?: string[];
            /** Audience */
            audience?: string[];
            /** Constraints */
            constraints?: string[];
            /** Performance Cues */
            performance_cues?: string[];
            /**
             * Custom Constraints
             * @default
             */
            custom_constraints: string;
            /**
             * Model Id
             * @default eleven_multilingual_v2
             */
            model_id: string;
            /**
             * Target Length
             * @default 5-7 minutes
             */
            target_length: string;
            /**
             * Cta
             * @default
             */
            cta: string;
            /** Knowledge Sources */
            knowledge_sources?: string[];
            /**
             * Source Focus
             * @default
             */
            source_focus: string;
        };
        /** PodcastRenderRequest */
        PodcastRenderRequest: {
            /** Voice Map */
            voice_map?: {
                [key: string]: string;
            };
            /**
             * Host Voice Id
             * @default
             */
            host_voice_id: string;
            /**
             * Guest Voice Id
             * @default
             */
            guest_voice_id: string;
            /**
             * Guest 2 Voice Id
             * @default
             */
            guest_2_voice_id: string;
            /**
             * Model Id
             * @default eleven_multilingual_v2
             */
            model_id: string;
            /** Stability */
            stability?: number | null;
            /** Similarity Boost */
            similarity_boost?: number | null;
            /** Style */
            style?: number | null;
            /** Speed */
            speed?: number | null;
            /** Use Speaker Boost */
            use_speaker_boost?: boolean | null;
        };
        /** PodcastSegment */
        PodcastSegment: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Turns */
            turns: components["schemas"]["PodcastTurn"][];
        };
        /** PodcastSpeaker */
        PodcastSpeaker: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @default
             */
            role: string;
            /** Voice Id */
            voice_id?: string | null;
        };
        /** PodcastTurn */
        PodcastTurn: {
            /** Id */
            id: string;
            /** Speaker Id */
            speaker_id: string;
            /** Text */
            text: string;
            /** Cues */
            cues?: components["schemas"]["PerformanceCue"][];
            /** Estimated Duration Seconds */
            estimated_duration_seconds?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoicePreviewRequest */
        VoicePreviewRequest: {
            /**
             * Text
             * @default This is a TellTales Ink voice preview.
             */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    options_api_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    content_generate_api_content_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_generate_api_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_generate_api_campaigns_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chapter_promos_generate_api_chapter_promos_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterPromoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drafts_api_drafts_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_draft_api_drafts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_draft_api_drafts__draft_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_draft_api_drafts__draft_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_draft_api_drafts__draft_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_script_api_podcasts_scripts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PodcastGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PodcastDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_create_script_api_podcasts_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PodcastGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_podcast_api_podcasts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PodcastDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_podcast_api_podcasts__draft_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PodcastDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    podcast_preview_api_podcasts__draft_id__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PodcastRenderRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    podcast_render_api_podcasts__draft_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PodcastRenderRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_api_exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_api_artifacts__artifact_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voices_api_voices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    voice_preview_api_voices__voice_id__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voice_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoicePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_status_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gallery_images_api_gallery_images_get: {
        parameters: {
            query?: {
                content_type?: string;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audio_library_api_library_audio_get: {
        parameters: {
            query?: {
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
