QUOTE_MOOD_TAGS = [
    "funny",
    "snarky",
    "sad",
    "tragic",
    "scary",
    "brutal",
    "roast",
    "savage",
    "romantic",
    "emotional",
    "dramatic",
    "iconic",
    "villainous",
    "grief",
    "revenge",
    "justice",
    "friendship",
    "betrayal",
    "survival",
    "media-satire",
    "Dominican-folklore",
    "Grim-Cojuelo",
]

QUOTE_BOOK_OPTIONS = [
    "Any book with approved quotes in the quote bank",
    "Mortal Vengeance",
    "Mortal Vengeance: A Grim Tale",
    "Mortal Vengeance II: To Reel or Not Too Real?",
]

CHARACTER_TAGS = [
    "Alex Herrera",
    "Melissa Rocha",
    "Mónika Torres",
    "Mario Stinga",
    "Manuel Freites",
    "Fernando Pepino",
    "Enrique Hartling",
    "María García",
    "Julián Díaz",
    "Lucía Salgado",
    "Profesora Lourdes",
    "Lieutenant Ricardo García",
    "The Grim Cojuelo",
]

AUDIENCE_OPTIONS = [
    "potential readers",
    "new readers",
    "existing fans",
    "BookTok readers",
    "Bookstagram readers",
    "influencers",
    "journalists",
    "reviewers",
    "ARC readers",
    "YA thriller readers",
    "horror readers",
    "dark academia readers",
    "general audience",
]

SOCIAL_OBJECTIVES = [
    "reach",
    "engagement",
    "comments",
    "shares",
    "saves",
    "tags",
    "follows",
    "clicks",
    "profile visits",
    "newsletter signups",
    "ARC signups",
    "preorders",
    "book sales",
    "reviews",
    "UGC / fan responses",
]

CONSTRAINT_OPTIONS = [
    "spoiler-free",
    "use only quote bank",
    "use only real reviews",
    "do not invent quotes",
    "do not invent reviews",
    "do not mention awards unless verified",
    "avoid major spoilers",
    "make it short",
    "make it punchy",
    "make it cinematic",
    "make it savage",
    "make it funny",
    "make it emotionally intense",
    "include CTA",
    "include hashtags",
    "no hashtags",
]

PLATFORM_OPTIONS = [
    "Instagram",
    "TikTok",
    "BookTok",
    "Bookstagram",
    "Goodreads",
    "YouTube",
    "newsletter",
    "blog",
    "press kit",
    "landing page",
]
